"""Add Telegram fields to User

Revision ID: 7840dc8cdb5b
Revises: 93c167e14543
Create Date: 2025-06-24 19:54:29.858449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7840dc8cdb5b'
down_revision: Union[str, None] = '93c167e14543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Для friends ---
    op.add_column('friends', sa.Column('status', sa.String(), nullable=True))
    op.add_column('friends', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('friends', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friends', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # --- Для users ---
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('allows_write_to_pm', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    # --- Заполняем новые поля дефолтными значениями для существующих строк ---
    from datetime import datetime
    now = datetime.utcnow()
    conn = op.get_bind()

    # Для friends
    conn.execute(
        sa.text("UPDATE friends SET status='accepted' WHERE status IS NULL")
    )
    conn.execute(
        sa.text("UPDATE friends SET created_at=:now WHERE created_at IS NULL"),
        {"now": now}
    )
    conn.execute(
        sa.text("UPDATE friends SET updated_at=:now WHERE updated_at IS NULL"),
        {"now": now}
    )

    # Для users
    conn.execute(
        sa.text("UPDATE users SET created_at=:now WHERE created_at IS NULL"),
        {"now": now}
    )
    conn.execute(
        sa.text("UPDATE users SET updated_at=:now WHERE updated_at IS NULL"),
        {"now": now}
    )
    # allows_write_to_pm пусть по умолчанию True
    conn.execute(
        sa.text("UPDATE users SET allows_write_to_pm=TRUE WHERE allows_write_to_pm IS NULL")
    )

    # --- Теперь меняем поля на NOT NULL ---
    op.alter_column('friends', 'status', nullable=False)
    op.alter_column('friends', 'created_at', nullable=False)
    op.alter_column('friends', 'updated_at', nullable=False)
    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'allows_write_to_pm')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    op.alter_column('friends', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friends', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('friends', 'updated_at')
    op.drop_column('friends', 'created_at')
    op.drop_column('friends', 'status')
    # ### end Alembic commands ###
