"""add invite_usage, event, hidden, created_at

Revision ID: fcab50bc945c
Revises: 2cc12f3469b7
Create Date: 2025-07-28 23:26:34.050424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab50bc945c'
down_revision: Union[str, None] = '2cc12f3469b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_invites_id'), 'friend_invites', ['id'], unique=False)
    op.create_index(op.f('ix_friend_invites_token'), 'friend_invites', ['token'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['friend_invites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('friends', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Является ли пользователь PRO',
               existing_nullable=False)
    op.alter_column('users', 'invited_friends_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Сколько друзей добавлено по инвайт-ссылке',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invited_friends_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Сколько друзей добавлено по инвайт-ссылке',
               existing_nullable=False)
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Является ли пользователь PRO',
               existing_nullable=False)
    op.drop_column('friends', 'hidden')
    op.drop_table('invite_usages')
    op.drop_table('events')
    op.drop_index(op.f('ix_friend_invites_token'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_id'), table_name='friend_invites')
    op.drop_table('friend_invites')
    # ### end Alembic commands ###
